# Run via: ansible-playbook (-K) ansible/account_create.yml -i inventory \
#            -e "hostname=<hostname> user=<username> password=<password>"
# Password will be hashed in parsing
---
- name: "Create a linux account, {{ user }}"
  hosts: "{{ hostname }}"
  become: yes
  roles:
    - role: 'roles/redata-account-create'
      vars:
        user: "{{ user }}"
        password: "{{ password }}"
        update_password: always
        ## Other options
        # state: present         # Ensure that account exists or to be created
        # shell: /bin/bash       # Defaults to /bin/bash
        # system: no             # Defaults to no (not system/sudo account)
        # create_home: yes       # Defaults to yes
        # generate_ssh_key: yes  # Defaults to yes
