# Run via: ansible-playbook (-K) ansible/account_create.yml -i inventory \
#            -e "hostname=<hostname> user=<username> password=<password>"
# Password must be hashed:
# python -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.using(rounds=5000).hash(getpass.getpass()))"
---
- name: Create a linux account
  hosts: "{{ hostname }}"
  tasks:
    - name: Create a login for {{ user }}
      user:
        name: "{{ user }}"
        password: "{{ password }}"
        update_password: always
        state: present
        shell: /bin/bash          # Defaults to /bin/bash
        system: no                # Defaults to no
        create_home: yes          # Defaults to yes
        home: "/home/{{ user }}"  # Defaults to /home/<username>
        generate_ssh_key: yes
